services:
  bot:
    build:
      context: . # где находится Dockerfile
      dockerfile: Dockerfile # Явно указываем Dockerfile
    image: ai_neuro_reception_bot:v1
    container_name: ai_neuro_reception_bot
    environment:
      - PYTHONUNBUFFERED=1 # Для отображения логов в реальном времени
    volumes:
      - /Users/aleksandrnikulin/work/UII/Ai Neuro Reception Bot:/proj/ai_neuro_reception_bot
    restart: unless-stopped
